//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("FRENDS Radon")]
[assembly: AssemblyDescription("FRENDS Radon")]
[assembly: AssemblyCompany("FRENDS Technology")]
[assembly: AssemblyProduct("FRENDS Radon")]
[assembly: AssemblyVersion("3.0.0.0")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

[assembly: AssemblyFileVersion("3.0.0.0")]
